# ---------------------------------------------------------------------------------------
# Protection Stones MongoDB Config
# ---------------------------------------------------------------------------------------
host: localhost
port: 27017
user: root
password: pass
databaselogin: Admin